export * from './cadastro/index'
export * from './dispositivos/index'
export * from './homepage/index'
export * from './login/index'
export * from './perfil/index'
export * from './perfilEditar/index'